on: push
name: Build project
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build and test
      uses: SAP/devops-docker-cx-server/mvn-github-action/monolith@ghact

