name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: actions/cache@preview
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: mvn -B install --file pom.xml -Dmaven.test.skip=true

    - name: Run unit tests
      run: mvn -B test surefire-report:report org.jacoco:jacoco-maven-plugin:0.8.5:report --file unit-tests/pom.xml

    - uses: actions/upload-artifact@master
      with:
        name: Unit Tests
        path: unit-tests/target
    - uses: actions/upload-artifact@master
      with:
        name: App
        path: application/target
